name: voice_call_core
description: Public Flutter plugin for Abber App voice calls with WebRTC, recording, and cloud storage support.
version: 1.0.0
homepage: https://github.com/AbberApp/voice_call_core
repository: https://github.com/AbberApp/voice_call_core
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

flutter:
  plugin:
    platforms:
      android:
        package: co.abber.voice_call_core
        pluginClass: VoiceCallCorePlugin
      ios:
        pluginClass: VoiceCallCorePlugin

dependencies:
  flutter:
    sdk: flutter
  flutter_webrtc: ^1.2.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
